### ISSUE TITLE
Please add to quicklisp

### ISSUE THREAD

**Issue by K1D77A** [shrdlu68/cl-tls#5]
Hi my latter-day-paypal library https://github.com/K1D77A/latter-day-paypal depends on this library to verify the integrity of webhooks sent from paypal, so I was wondering if you could either give me permission to ask Xach to add this to QL or if you could ask yourself @ https://github.com/quicklisp/quicklisp-projects/issues 

Thanks :+1:

**Comment by shrdlu68** [comment]
Hi, feel free to go ahead and add it to Quicklisp.

**Comment by K1D77A** [comment]
Thanks :+1:
